# Generated by Django 3.1.7 on 2021-03-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingurl',
            name='bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interestingurl',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interestingurl',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interestingurl',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interestingurl',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='non_interestingurl',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
