# Generated by Django 3.1.7 on 2021-03-21 22:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210322_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='interestingurl',
            name='group',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
    ]
